name: ArmyPlanner

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows workflow to be ran via a button
  
jobs:
  build:

    runs-on: ubuntu-latest
    name: Build
    env:
      config: 'Release'
      framework: 'net6.0'

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore ArmyPlanner.Pages/ArmyPlanner.Pages.csproj

    - name: Build
      run: dotnet publish ArmyPlanner.Pages/ArmyPlanner.Pages.csproj --no-restore -f $framework -c $config
      
    - name: Directory
      run: |
        cd ArmyPlanner.Pages
        dir

    - name: Change base-tag in index.html from / to armyplanner
      run: sed -i ‘s/<base href=”\/” \/>/<base href=”\/armyplanner\/” \/>/g’ ArmyPlanner.Pages/bin/${{env.config}}/${{env.framework}}/publish/wwwroot/index.html

    - name: copy index.html to 404.html
      run: cp ArmyPlanner.Pages/bin/${{env.config}}/${{env.framework}}/publish/wwwroot/index.html ArmyPlanner.Pages/bin/${{env.config}}/${{env.framework}}/publish/wwwroot/404.html
      
    - name: Publish Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: pages
        path: ArmyPlanner.Pages/bin/${{env.config}}/${{env.framework}}/publish/wwwroot/
      
  deploy:
    needs: build 
    runs-on: ubuntu-latest
    name: Deploy
    steps:

    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: pages
        path: dist      
        
    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: ./dist/
        jekyll: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
